# Generated by Django 4.2.5 on 2025-02-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('scheme', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='api.league')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Match_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('captain', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('A', 'Goalkeepers'), ('B', 'Defenders'), ('C', 'Midfielders'), ('D', 'Forwards')], default='M', max_length=1)),
                ('name', models.CharField(max_length=64)),
                ('number', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['type', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.match')),
                ('match_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.match_player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6)),
                ('players', models.ManyToManyField(blank=True, to='api.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='match_player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player'),
        ),
        migrations.AddField(
            model_name='match_player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_local', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_visit', to='api.team'),
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, to='api.team'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Admin'), ('B', 'Staff'), ('C', 'Branded'), ('D', 'Users')], default='D', max_length=1)),
                ('verification', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=100)),
                ('birthday', models.DateField()),
                ('team', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'match'), name='unique_vote_per_user_match'),
        ),
        migrations.AddConstraint(
            model_name='match_player',
            constraint=models.UniqueConstraint(fields=('match', 'team', 'player'), name='unique_match_team_player'),
        ),
    ]
