# Generated by Django 4.2.5 on 2025-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_league_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='manual_votes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match_player',
            name='manual_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('A', 'Admin'), ('B', 'Staff'), ('C', 'Branded'), ('D', 'Users'), ('E', 'Switch')], default='D', max_length=1),
        ),
    ]
