# Generated by Django 4.2.5 on 2025-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_match_manual_votes_match_player_manual_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fullname',
            field=models.CharField(default='', max_length=64),
        ),
    ]
