services:

  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: server-backend
    restart: always
    env_file:
      - ../.env
    environment:
      - PRODUCTION=${PRODUCTION}
    volumes:
      - ..:/app
    ports:
      - 80:8000

  # webserver:
  #   container_name: server-webserver
  #   restart: always
  #   image: nginx:stable-alpine
  #   depends_on:
  #     - backend
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./conf/nginx:/etc/nginx/conf.d
